### Site settings
lang: en
title: "Game Z"
description: "Game Z"
#meta_description: "default meta tag description.Google does not recommend that all pages have the same description"
#meta_keywors: "default meta tag keywors.Google does not recommend that all pages have the same description"
#author: "Your name"
#since: "Your site is since YYYY"
#baseurl: "/my_dir"
exclude: [ "README.md", "LICENSE", "Gemfile", "Gemfile.lock", "rindow-ghpages-bootstrap.gemspec" ]
url: "https://game-z.github.io"
#email: your-email@domain.com
#twitter_username: your_twitter_username
#github_username:  your_github_username
google_analytics_id: UA-12321104-11
#google_site_verification: XXXXXXXXXXXXXXXXXXXXXXXXXXX
#google_custom_search_engine_id: "XXXXXXXX:XXXXXXXXXXXXXXXXXXX"
#disqus_shortname: your_disqus_shortname

### Build settings
plugins:
  - jekyll-paginate
permalink: "/blog/:year/:month/:day/:title.html"
images_path: "/assets/img/"
sass:
  style: :compressed
#markdown: kramdown
#gems: [jekyll-test-plugin, jekyll-jsonify, jekyll-assets]

### Appearance
appearance:
  theme: default
  ###
  ### Example to enable a wallpaper.
  ###
  #header_text_color: "brown"
  #header_image: none
  #wallpaper_image: /assets/themes/default/img/wallpaper.png
  #wallpaper_repeat: repeat

### Blog
#blogpagination: true
#paginate: 5
#paginate_path: "blog/page:num/" # DON'T TOUCH THIS PATH.
#blog:
#  title: "Blog Title"
#  description: "Blog description"
#  title_position: article
#  enable_author: true
#  comment: true
#  share: true
#  category: true
  #sidearea:
  #  primary:
  #    widgets:
  #    - { widget: categories, caption: "Categories" }
  #    - { widget: recentposts, caption: "Recent Posts" }
  #    - { widget: subscribe, caption: "Subscribe" }
  #theme: blog

### Navigation Bar
sitesearchscript: true
#navbar:
#  menu:
#    - caption: "Projects"
#      menu:
#        - { caption: "Creating Web pages", link: "#"}
#        - { caption: "Something else here", link: "#"}
#        - { separator: "divider" }
#        - { caption: "miscellaneous", separator: "dropdown-header" }
#        - { caption: "Downloads", link: "#"}
#    - { caption: "Blog", link: "/blog/" }
#    - { caption: "Documents", link: "/docs/" }
#    - { caption: "Help", link: "/help/" }
#    - { caption: "Sitemap", link: "/sitemap/" }
#    - { caption: "About", link: "/about/" }

footer:
  links:
    #- { caption: "About", link: "/about/" }
    #- { caption: "Sitemap", link: "/sitemap/" }

### Document collections
collections:
  avabel:
    permalink: "/:collection/:title:output_ext"
    no_ext: true
    lang: ja
    theme: avabel
    title: "アヴァベル オンライン攻略(アイテム事典)"
    description: アヴァベルオンライン攻略データ。武器やアイテムの入手場所・強化方法・使い道などを中心に掲載。
    keywords: アヴァベル攻略,アヴァベルオンライン,AVABEL ONLINE
    output: true
    navigator: disable
    search_engine_id: "012660066390906066162:4vjjdvvbdes"
    sidearea:
      top:
        cache: true
        widgets:
          #- { widget: free-area, name: avabel, item: top }
          - { widget: navb, name: avabel, item: menu, inline: true }
      primary:
        cache: true
        widgets:
          - { widget: free-area, name: ads, item: side }
          - { widget: navv, name: avabel, item: menu, anchor: menu }
      header:
        cache: true
        widgets:
          #- { widget: free-area, name: ads, item: mobile100 }
      #floating:
      #  cache: true
      #  widgets:
      #    - { widget: free-area, name: mobile }

  minecraft:
    permalink: "/:collection/:title:output_ext"
    no_ext: true
    lang: ja
    theme: minecraft
    title: "マイクラPE攻略(アイテム＆レシピ)"
    description: "ver1.1対応。『マインクラフト Pocket Edition』の攻略データ。アイテムとレシピ(アイテムの作り方と材料)に関する情報を中心に掲載。検索もできます。"
    keywords: "Minecraft,Pocket Edition,Wiki"
    meta_description: disable
    output: true
    navigator: disable
    search_engine_id: "012660066390906066162:th5euhneknw"
    sidearea:
      top:
        cache: true
        widgets:
          - { widget: navb, name: minecraft, item: menu, inline: true }
          #- { widget: search, inline: true }
      primary:
        cache: true
        widgets:
          - { widget: free-area, name: ads, item: side }
          - { widget: navv, name: minecraft, item: menu, anchor: menu }
      header:
        cache: true
        widgets:
          #- { widget: free-area, name: ads, item: mobile100 }
      #floating:
      #  cache: true
      #  widgets:
      #    - { widget: free-area, name: mobile }

  minecraft_en:
    permalink: "/:collection/:title:output_ext"
    no_ext: true
    lang: en
    theme: minecraft
    title: "Minecraft PE Crafting Recipes"
    description: "Game reference guide for Minecraft (Bedrock Edition). We focus on crafting recipes (Items,Materials,Methods)."
    keywords: "Minecraft,Pocket Edition,Wiki"
    meta_description: disable
    output: true
    navigator: disable
    search_engine_id: "012660066390906066162:8g7g-w3nf1u"
    sidearea:
      top:
        cache: true
        widgets:
          - { widget: navb, name: minecraft_en, item: menu, inline: true }
          #- { widget: search, inline: true }
      primary:
        cache: true
        widgets:
          - { widget: free-area, name: ads, item: side }
          - { widget: navv, name: minecraft_en, item: menu, anchor: menu }
      header:
        cache: true
        widgets:
          #- { widget: free-area, name: ads, item: mobile100 }
      #floating:
      #  cache: true
      #  widgets:
      #    - { widget: free-area, name: mobile }
