### Site settings
lang: en
title: "Game Z"
description: "Game Z"
#meta_description: "default meta tag description.Google does not recommend that all pages have the same description"
#meta_keywors: "default meta tag keywors.Google does not recommend that all pages have the same description"
#author: "Your name"
#since: "Your site is since YYYY"
#baseurl: "/my_dir"
exclude: [ "README.md", "LICENSE", "Gemfile", "Gemfile.lock", "rindow-ghpages-bootstrap.gemspec" ]
url: "https://game-z.github.io"
#email: your-email@domain.com
#twitter_username: your_twitter_username
#github_username:  your_github_username
#google_analytics_id: UA-XXXXXXXX-XX
#google_site_verification: XXXXXXXXXXXXXXXXXXXXXXXXXXX
#google_custom_search_engine_id: "XXXXXXXX:XXXXXXXXXXXXXXXXXXX"
#disqus_shortname: your_disqus_shortname

### Build settings
plugins:
  - jekyll-paginate
permalink: "/blog/:year/:month/:day/:title.html"
images_path: "/assets/img/"
sass:
  style: :compressed
#markdown: kramdown
#gems: [jekyll-test-plugin, jekyll-jsonify, jekyll-assets]

### Appearance
appearance:
  theme: default
  ###
  ### Example to enable a wallpaper.
  ###
  #header_text_color: "brown"
  #header_image: none
  #wallpaper_image: /assets/themes/default/img/wallpaper.png
  #wallpaper_repeat: repeat

### Blog
blogpagination: true
paginate: 5
paginate_path: "blog/page:num/" # DON'T TOUCH THIS PATH.
blog:
  title: "Blog Title"
  description: "Blog description"
  title_position: article
  enable_author: true
  comment: true
  share: true
  category: true
  #sidearea:
  #  primary:
  #    widgets:
  #    - { widget: categories, caption: "Categories" }
  #    - { widget: recentposts, caption: "Recent Posts" }
  #    - { widget: subscribe, caption: "Subscribe" }
  #theme: blog

### Navigation Bar
sitesearchscript: true
navbar:
  menu:
    - caption: "Projects"
      menu:
        - { caption: "Creating Web pages", link: "#"}
        - { caption: "Something else here", link: "#"}
        - { separator: "divider" }
        - { caption: "miscellaneous", separator: "dropdown-header" }
        - { caption: "Downloads", link: "#"}
    - { caption: "Blog", link: "/blog/" }
    - { caption: "Documents", link: "/docs/" }
    - { caption: "Help", link: "/help/" }
    - { caption: "Sitemap", link: "/sitemap/" }
    - { caption: "About", link: "/about/" }

footer:
  links:
    - { caption: "About", link: "/about/" }
    - { caption: "Sitemap", link: "/sitemap/" }

### Document collections
collections:
  docs:
    #permalink: "/:collection/:title:output_ext"
    title: "Documents"
    description: "some description"
    #meta_description: "default meta tag description.Google does not recommend that all pages have the same description"
    #meta_keywors: "default meta tag keywors.Google does not recommend that all pages have the same description"
    output: true
    #theme: docs
    comment: true
    share: true
    #lang: en
    #navigator: disable
    sidearea:
      primary:
        widgets:
        - { widget: search, caption: "Search" }
        - { widget: navv, name: docs, item: menu, caption: "Menu", anchor: "menu" }
        - { widget: free-area, name: docs, item: menu, markdownify: true }
        - { widget: nav, name: docs, item: toc, caption: "Contents" }

  avabel:
    permalink: "/:collection/:title:output_ext"
    no_ext: true
    lang: ja
    theme: avabel
    title: "アヴァベル オンライン攻略(アイテム事典)"
    description: アヴァベルオンライン攻略データ。武器やアイテムの入手場所・強化方法・使い道などを中心に掲載。
    keywords: アヴァベル攻略,アヴァベルオンライン,AVABEL ONLINE
    output: true
    navigator: disable
    sidearea:
      top:
        cache: true
        widgets:
          - { widget: free-area, name: avabel, item: top }
          - { widget: search }
      primary:
        cache: true
        widgets:
          - { widget: free-area, name: ads, item: side }
          - { widget: free-area, name: avabel, item: menu, markdownify: true }
      header:
        cache: true
        widgets:
          - { widget: free-area, name: ads, item: mobile100 }
      #floating:
      #  cache: true
      #  widgets:
      #    - { widget: free-area, name: mobile }

  minecraft:
    permalink: "/:collection/:title:output_ext"
    no_ext: true
    lang: ja
    theme: minecraft
    title: "マイクラPE攻略(アイテム＆レシピ)"
    description: "ver1.1対応。『マインクラフト Pocket Edition』の攻略データ。アイテムとレシピ(アイテムの作り方と材料)に関する情報を中心に掲載。検索もできます。"
    keywords: "Minecraft,Pocket Edition,Wiki"
    meta_description: disable
    output: true
    navigator: disable
    sidearea:
      top:
        cache: true
        widgets:
          - { widget: navb, name: minecraft, item: menu, inline: true }
          #- { widget: search, inline: true }
      primary:
        cache: true
        widgets:
          - { widget: free-area, name: ads, item: side }
          - { widget: free-area, name: minecraft, item: menu, markdownify: true }
      header:
        cache: true
        widgets:
          - { widget: free-area, name: ads, item: mobile100 }
      #floating:
      #  cache: true
      #  widgets:
      #    - { widget: free-area, name: mobile }
